use nopeat_core::fusion::suffix_match;
use nopeat_core::model::{
    Asset, Chunk, Module, Severity, SizeDimension, SizeSet, UnifiedBundleGraph,
};
use nopeat_core::sizes;
use nopeat_core::sourcemap::parse_bytes;
use proptest::prelude::*;

const B64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

fn vlq(value: i64) -> String {
    let mut v = if value < 0 { ((-value) << 1) | 1 } else { value << 1 };
    let mut out = String::new();
    loop {
        let mut digit = usize::try_from(v & 31).unwrap_or(0);
        v >>= 5;
        if v > 0 {
            digit |= 32;
        }
        out.push(B64[digit] as char);
        if v == 0 {
            return out;
        }
    }
}

fn map_with_segments(offsets: &[u32]) -> Vec<u8> {
    use std::fmt::Write as _;

    let sources: Vec<String> =
        (0..offsets.len()).map(|i| format!("\"webpack://fixture/./src/module-{i}.ts\"")).collect();
    let mut mappings = String::new();
    let mut prev = 0u32;
    for (i, offset) in offsets.iter().enumerate() {
        if i > 0 {
            mappings.push(',');
        }

        let _ = write!(
            mappings,
            "{}{}{}{}",
            vlq(i64::from(*offset - prev)),
            vlq(i64::from(i > 0)),
            vlq(i64::from(i > 0)),
            vlq(0)
        );
        prev = *offset;
    }
    format!(
        r#"{{"version":3,"file":"bundle.js","sources":[{}],"sourcesContent":[],"names":[],"mappings":"{}"}}"#,
        sources.join(","),
        mappings
    )
    .into_bytes()
}

proptest! {

    #[test]
    fn attribution_sums_to_the_generated_length(offsets in prop::collection::vec(0u32..50_000, 1..24)) {
        let mut sorted = offsets;
        sorted.sort_unstable();
        sorted.dedup();
        prop_assume!(sorted.len() >= 2);

        let generated = u64::from(sorted.last().copied().unwrap()) + 4_321;
        let map = parse_bytes(&map_with_segments(&sorted)).expect("valid map");

        let by_source = map.attribute_by_source_in(generated);
        let total: u64 = by_source.iter().map(|(_, bytes)| bytes).sum();
        let prologue = u64::from(sorted[0]);
        prop_assert_eq!(
            total,
            generated - prologue,
            "attributed {} of {} generated bytes ({} before the first mapping)",
            total,
            generated,
            prologue
        );

        for (index, bytes) in &by_source {
            prop_assert!(*index < sorted.len(), "source index {} out of range", index);
            prop_assert!(*bytes > 0, "a zero-byte source must not be listed");
        }
    }

    #[test]
    fn decoded_offsets_are_the_cumulative_deltas(
        deltas in prop::collection::vec(1u32..5_000, 1..20),
    ) {
        let mut offsets = Vec::with_capacity(deltas.len());
        let mut acc = 0u32;
        for d in &deltas {
            acc += d;
            offsets.push(acc);
        }
        let map = parse_bytes(&map_with_segments(&offsets)).expect("valid map");
        let decoded: Vec<u32> = map.mappings.iter().map(|m| m.generated_offset).collect();
        prop_assert_eq!(decoded, offsets);

        for pair in map.mappings.windows(2) {
            prop_assert!(
                pair[0].generated_offset <= pair[1].generated_offset,
                "offsets must not go backwards: {} then {}",
                pair[0].generated_offset,
                pair[1].generated_offset
            );
        }
    }

    #[test]
    fn suffix_matching_is_segment_aligned(path in "[a-zA-Z0-9_./-]{1,64}") {
        prop_assert!(suffix_match(&path, &path), "a path must match itself: {}", path);

        let stem = format!("{}-ish", path.trim_end_matches('/'));
        prop_assert!(
            !suffix_match(&stem, &path) || stem.ends_with(&path),
            "`{}` matched `{}` on a partial segment",
            stem,
            path
        );
    }

    #[test]
    fn a_webpack_url_matches_its_relative_path(name in "[a-zA-Z0-9_.-]{1,24}") {
        let prefixed = format!("webpack://fixture/./src/{name}.ts");
        let relative = format!("./src/{name}.ts");
        prop_assert!(
            suffix_match(&relative, &prefixed),
            "`{}` should match `{}`",
            relative,
            prefixed
        );
    }
}

#[test]
fn a_measurement_smaller_than_the_claim_is_still_labelled_parsed() {
    let dir = std::env::temp_dir().join("nopeat-property-scaled");
    std::fs::create_dir_all(&dir).expect("temp dir");
    let on_disk = 400_000usize;
    std::fs::write(dir.join("main.js"), vec![b'x'; on_disk]).expect("write asset");
    let mut graph = UnifiedBundleGraph::new();
    graph.assets.push(Asset {
        name: "main.js".into(),
        size: on_disk as u64,
        chunks: vec![0],
        sizes: SizeSet { stat: 1_000_000, parsed: on_disk as u64, ..SizeSet::default() },
    });
    graph.chunks.push(Chunk {
        id: 0,
        names: vec!["main".into()],
        initial: true,
        assets: vec!["main.js".into()],
        size: SizeSet { stat: 1_000_000, ..SizeSet::default() },
    });
    graph.modules.insert(
        "./src/big.js".into(),
        Module {
            id: "./src/big.js".into(),
            name: "./src/big.js".into(),
            issuer: None,
            reasons: vec![],
            package: None,
            chunks: vec![0],
            sizes: SizeSet { stat: 900_000, ..SizeSet::default() },
            attribution_delta: 0,
            sources: vec![],
        },
    );

    sizes::attribute_from_disk(&mut graph, &dir, sizes::Compression::Gzip)
        .expect("the asset is on disk");

    let module = &graph.modules["./src/big.js"];

    assert_eq!(module.sizes.parsed, 360_000, "scaled by the measured asset");
    assert!(module.sizes.parsed < module.sizes.stat);

    assert_eq!(graph.totals.size_dimension, SizeDimension::Parsed);

    let empty = std::env::temp_dir().join("nopeat-property-missing");
    std::fs::create_dir_all(&empty).expect("temp dir");

    let mut graph2 = UnifiedBundleGraph::new();
    graph2.assets.push(Asset {
        name: "main.js".into(),
        size: 1_000_000,
        chunks: vec![0],
        sizes: SizeSet { stat: 1_000_000, ..SizeSet::default() },
    });
    graph2.chunks.push(Chunk {
        id: 0,
        names: vec!["main".into()],
        initial: true,
        assets: vec!["main.js".into()],
        size: SizeSet { stat: 1_000_000, ..SizeSet::default() },
    });
    sizes::attribute_from_disk(&mut graph2, &empty, sizes::Compression::Gzip)
        .expect("a missing asset is not fatal");
    let asset = graph2.assets.iter().find(|a| a.name == "main.js").expect("asset");

    assert_eq!(asset.sizes.parsed, 0, "no measurement means no parsed size");
    assert_eq!(asset.sizes.stat, 1_000_000, "the declared size stands, not zero");
    let diagnostic = graph2
        .diagnostics
        .iter()
        .find(|d| d.code == "NPT0002")
        .expect("a missing asset must be reported");
    assert_eq!(diagnostic.severity, Severity::Info, "it is not a build-breaking error");
}

#[test]
fn a_corrupt_delta_is_rejected_not_wrapped() {
    let raw = br#"{"version":3,"file":"b.js","sources":["a.ts"],"names":[],"mappings":"2gB"}"#;
    match parse_bytes(raw) {
        Err(_) => {}
        Ok(map) => {
            for m in &map.mappings {
                assert!(
                    m.generated_offset < 1_000_000,
                    "a corrupt delta produced offset {}",
                    m.generated_offset
                );
            }
        }
    }

    let good = br#"{"version":3,"file":"b.js","sources":["a.ts"],"names":[],"mappings":"AAAA"}"#;
    assert!(parse_bytes(good).is_ok());
}
